### PR TITLE
[Feat]: Add stroke and roundness styling options to grapples

### PR DESCRIPTION
**Pull request by absharma9796**
# Why Changes?

Currently grapples do not support configuring `stroke` or `corner radius` options.

# What Changes?

Support for 3 new options

```js
grappleStrokeColor: "black", // stroke color of the grapples
grappleStrokeWidth: 0, // stroke width of the grapples
grappleCornerRadius: 0, // corner radius of the grapples
```

# Usage

```js
cy.nodeEditing({
      ...
      grappleStrokeColor: "black",
      grappleStrokeWidth: 2,
      grappleCornerRadius: 2,
      ...
})
```

### CODE REVIEW

**Comment by ugurdogrusoz** [comment]
@osamazafar980 Please review and merge if OK

**Comment by absharma9796** [comment]
@osamazafar980 Ping

**Comment by absharma9796** [comment]
@osamazafar980 When can this be merged to master?

**Comment by ugurdogrusoz** [comment]
@absharma9796 we do not do frequent releases due to lack of resources. Feel free to use it out of the unstable branch though.

**Pull request merged**
